Fixes for V2 for alpine, rhel, nvd, and ubuntu
quay/clair pull request #1021
Opened 2020-07-29 00:20 UTC by nycnewman

Signed-off-by: nycnewman <edward@digitalasset.com>

several: Fixes for NVD, RHEL, ubuntu, and alpine

NVD - switch to JSON V1.1 data feeds and use CVSS V3 scores
RHEL - fix to correctly handle vulnerabilities where severity tagged as None
Ubuntu - fix for multiple packages in name (should created unique versions in DB for each referenced package)
alpine - backport of fix I made for V3 to use new web site to download alpine vuln data

Test process:
- spin up new clean DB 
- load clair in debug mode and wait to pull all vuln data
- test some images (alpine:3.9.4 and internal docker) to get results using klar, paclair and clair-scanner

Fixes #966 #1013 #843 #916

2020-08-03 17:14 UTC, ldelossa requested changes

2020-08-03 17:14 UTC, ldelossa commented on go.mod
> +	github.com/coreos/clair v2.1.0+incompatible // indirect
why is this import added?

2020-08-03 17:14 UTC, ldelossa commented on ext/vulnsrc/ubuntu/ubuntu.go
> +					featureVersion := database.FeatureVersion{
quick explanation of why this change is necessary?

2020-08-03 17:14 UTC, ldelossa commented on ext/vulnsrc/rhel/rhel.go
> +		return database.NegligibleSeverity
:+1:

2020-08-03 18:14 UTC, nycnewman commented on ext/vulnsrc/ubuntu/ubuntu.go
> +					featureVersion := database.FeatureVersion{
There is an odd message produced by Clair when parsing Ubuntu vulnerabilities. Appears that some vulns show multiple fix versions and code assumes only one. The code splits based on comma and adds each. This is seen in issue #966 with entry:

precise_pgpdump: released (0.27-1+deb7u1build0.12.04.1, 0.28-1+deb8u1)

However I am aware but less knowledgeable on some entries where the second element shows "revisions" and a number, i.e. 

snap_subiquity: released (20.05.2, revisions 1873+)

so code fix might introduce different issues. 

Separately there also appear to be an issue I haven't yet resolved where Ubuntu shows "snap" as the build. This is seen in CVE-2020-11932 (and others). Seems someone is tagging certain snap packages as snap rather than each Ubuntu build (trusty, xenial, etc). The above entry also shows this problem (see snap before underscore)

snap_subiquity: released (20.05.2, revisions 1873+)

This throws an issue about Clair needing to be updated from update.go

2020-08-03 18:16 UTC, nycnewman commented on go.mod
> +	github.com/coreos/clair v2.1.0+incompatible // indirect
No idea. Removed

2020-08-03 18:19 UTC, nycnewman commented
@ldelossa just to confirm. V2 branch seems to be relatively stable and has formal releases (2.1.4 seems to be latest). V3 API appears to be out there and on master. But comments in Git and elsewhere seems to imply that V3 branch is stagnant and that Quay is working on a new V4 code base. Not expecting things like Python or NPM to make it to V2 releases. There appears to be code but unreviewed in a long time

2020-08-03 22:40 UTC, ldelossa commented
@nycnewman your assumption is correct. v2 is the most deployed and stable version. v3 wont be further developed, and v4 is currently under heavy development and will succeed all previous. V4 currently supports Python.

2020-08-03 22:42 UTC, ldelossa commented on ext/vulnsrc/ubuntu/ubuntu.go
> +					featureVersion := database.FeatureVersion{
Got it, the way V4 does classification is quiet different, id assume more accuracy with V4, if you have time give it a try.

2020-08-03 23:51 UTC, nycnewman commented
Any way to kick Travis to confirm build?

2020-08-06 15:04 UTC, ldelossa commented
weird, let me see if I can get travis to do it's thing.

2020-08-06 15:15 UTC, ldelossa commented
@nycnewman because of your comments here:
```
so code fix might introduce different issues.
```

Can you do some comparisons on reported vulnerabilities between Ubuntu, RHEL, etc.. images in this branch and the current HEAD?

2020-08-27 00:07 UTC, nycnewman commented
Leonid - still looking into this. Initial comparison of initial load between version shows expected increase in vulns for alpine (switch from repo to web site). However seeing other odd behaviour even for current release of duplicate vulns getting into database. Only difference between rows appears to be NVD data set (second has no CVSS V3 score).

Is there a standard test you have to check regressions like this? Recommendations on how to check new releases. I'm doing PostgresQL queries at the moment to investigate changes.

2020-08-29 14:51 UTC, nycnewman commented
Louis - based on my analysis of the DB after one load the diff I see between current release and my PR is primarily additional vulns for alpine based on new source. this is expected and correct. All other platforms have same could of vulns.

2020-09-04 02:29 UTC, digitalasset-cla commented
... same count of ...

2020-09-28 08:17 UTC, byteborg commented
Could you split out the update for the NVD sources and give it a fast-lane, please?
Apparently, missing the NVD feed results in inconsistent/missing criticality values, thus results that were once "Critical" are evaluated as "Unknown". 

I am using a dockerized scan container and made a test case against a specific version of WebGoat 8, that normally yields several vulns. When the NVD 1.0 feed is not available, classification apparently breaks. This is really bad.

2020-09-28 14:06 UTC, nycnewman commented
@byteborg this is just waiting on approval from @ldelossa . Seems focus is now on Clair V4 so this is outstanding.

2020-09-28 18:43 UTC, ldelossa commented
@nycnewman 

Do you feel confident in merging this? As stated on our mailing list our ClairV2 and ClairV3 will be community maintained. Any issues moving forward will have to be patched by community contribution.

2020-09-28 18:45 UTC, nycnewman commented
My testing shows the delta is expected based on new alpine changes. Think there may be an issue with V2 branch around updating database but believe this to be existing before this change.

2020-09-28 18:47 UTC, ldelossa commented
@nycnewman great, can you rebase and I will approve and merge and then schedule a release.

2020-09-28 18:50 UTC, ldelossa submitted a review, later dismissed

2020-10-01 09:37 UTC, sdd commented
@ldelossa are you able to approve & merge, now that @nycnewman has rebased as you requested? Thanks

2020-10-01 11:13 UTC, ldelossa approved these changes

2020-10-01 11:13 UTC, merged

2020-10-01 11:14 UTC, ldelossa commented
@sdd @nycnewman its in. 

Ill issue a release in just a bit and ping you both.

2020-10-01 12:52 UTC, ldelossa commented
@sdd @nycnewman 

Released: 

`quay.io/coreos/clair:v2.1.6`

2020-10-01 13:09 UTC, nycnewman commented
Excellent. Thank you