docs: rework mdbook
quay/clair pull request #1036
Opened 2020-09-03 19:39 UTC by ldelossa

this commit overhauls the ClairV4 documentation

Signed-off-by: ldelossa <ldelossa@redhat.com>

2020-09-10 19:36 UTC, hdonnay requested changes

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts.md
> +The following sections give a conceptual overview of how ClairCore works internally.
```suggestion
The following sections give a conceptual overview of how Clair works internally.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/api_internal.md
> +The `update_operation` endpoint exposes the api for viewing updater's activity.
```suggestion
The `update_operation` endpoint exposes the api for viewing updaters' activity. 
```
Plural possessive

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/authentication.md
> +# Authentication
The whole bottom half of this file has nothing to do with Authentication, this seems like an odd spot for it.

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/indexing.md
> +Indexing involves taking a manifest representing a container image and computing its constinuent parts. The indexer is trying to understand what packages exist in the image, what distribution the ima
```suggestion
Indexing involves taking a manifest representing a container image and computing its constituent parts. The indexer is trying to discover what packages exist in the image, what distribution the image is derived from, and what package repositories are used within the image. Once this information is computed it is persisted in an IndexReport.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/indexing.md
> +
```suggestion
The IndexReport is an intermediate data structure describing the contents of a container image. This report can be fed to a [Matcher](../reference/matcher.md) node for vulnerability analysis.

```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/indexing.md
> +ClairV4 treats all manifests and layers as [content addressable](https://en.wikipedia.org/wiki/Content-addressable_storage). In the context of ClairV4 this means once we index a specific manifest we
```suggestion
ClairV4 treats all manifests and layers as [content addressable](https://en.wikipedia.org/wiki/Content-addressable_storage). In the context of ClairV4 this means once we index a specific manifest we will not index it again unless it's required, and likewise with individual layers. This allows a large reduction in work. 
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/indexing.md
> +For example consider how many images in a registry may use "ubuntu:artful" as a base layer. It could be a large majority of images if the developers prefer basing their images off ubuntu. Treating th
```suggestion
For example, consider how many images in a registry may use "ubuntu:artful" as a base layer. It could be a large majority of images if the developers prefer basing their images off ubuntu. Treating the layers and manifests as content addressable means we will only fetch and scan the base layer once.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/indexing.md
> +When ClairV4 update an internal component such as a package scanner and is asked to index a layer it will know to perform the scan with the new package scanner. ClairV4 is smart enough to understand
```suggestion
When an internal component such as a package scanner is updated, Clair will know to perform the scan with the new package scanner. Clair has enough information to determine that a component has changed and the IndexReport may be different this time around. 
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/indexing.md
> +A client can track ClairV4's `index_state` endpoint to understand when an internal component has changed, and subsequent issue re-indexes. See our [api](../howto/api.md) guide to learn how to view ou
```suggestion
A client can track ClairV4's `index_state` endpoint to understand when an internal component has changed and subsequently issue re-indexes. See our [api](../howto/api.md) guide to learn how to view our api specification.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/indexing.md
> +## Summary
Why is the summary at the end?

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/indexing.md
> +In summary you should understand that Indexing is the process ClairV4 uses to understand the contents of a container.
```suggestion
In summary, you should understand that Indexing is the process Clair uses to understand the contents of layers.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/matching.md
> +Matchers by default are also responsible for keeping the database of vulnerabilities up to date. Matchers will typically run a set of Updaters which periodically probe their data sources for new cont
```suggestion
Matchers by default are also responsible for keeping the database of vulnerabilities up to date. Matchers will typically run a set of Updaters which periodically probe their data sources for new contents, storing new vulnerabilities in the database when discovered.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/matching.md
> +The matcher API is designed to be called often and will always provide the most up-to-date VulnerabilityReport when queried. This VulnerabilityReport summaries both the container's contents and any v
```suggestion
The matcher API is designed to be called often and will always provide the most up-to-date VulnerabilityReport when queried. This VulnerabilityReport summaries both a manifest's contents and any vulnerabilities affecting the contents.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/matching.md
> +## Summary
Summary at the end?

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/notifications.md
> +The interested client can subscribe to notifications via several substrates:
```suggestion
The interested client can subscribe to notifications via several mechanisms:
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/notifications.md
> +When the notifier becomes aware of new vulnerabilities affecting an index manifest it will inform the client of the change. The client will receive a single notification expressing the **most servere
```suggestion
When the notifier becomes aware of new vulnerabilities affecting a previously indexed manifest, it will use the configured method(s) to issue notifications about the new changes. Any given notification expresses the **most severe** vulnerability discovered because of the change. This avoids creating a flurry of notifications for the same security database update. 
```

Isn't the "single, most severe" heuristic specific to the webhook mechanism? I don't recall, just want to double-check.

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/notifications.md
> +Once a client receives this notification they should issue a new request again the [matcher](../reference/matcher.md) to receive a up-to-date vulnerability report.
```suggestion
Once a client receives a notification, it should issue a new request against the [matcher](../reference/matcher.md) to receive an up-to-date vulnerability report.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/notifications.md
> +The notification schema will be the json mashalled form of the following schema:
```suggestion
The notification schema is the JSON marshaled form of the following types:
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/notifications.md
> +*See the "Notifier.Webhook" object in our [config reference](../reference/config.md) for complete configuration details.*
```suggestion
*See the "Notifier.Webhook" object in the [config reference](../reference/config.md) for complete configuration details.*
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/notifications.md
> +  "callback": {url_to_notifications}
```suggestion
  "notification_id": "<uuid>",
  "callback": "<url>"
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/notifications.md
> +When the notifier has determined an updated security database has changed the affected status of an indexed container it will deliver the following json body to the configured target:
```suggestion
When the notifier has determined an updated security database has changed the affected status of an indexed manifest, it will deliver the following JSON body to the configured target:
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/notifications.md
> +On receipt the client can immediately browse to the URL provided in the callback field.
```suggestion
On receipt, the server can immediately browse to the URL provided in the callback field.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/notifications.md
> +```go
`go` isn't the correct type for this snippet. Should just have no type.

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/notifications.md
> +The "next" url param informs Clair the next set of paged notifications to return. If not provided
Unfinished

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/notifications.md
> +A page object is returned which specifies "next" and "size" fields.
There's a `page` object inside the returned object, it's not the returned object

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/notifications.md
> +While not manditory the client may issue a delete of the notification via the DELETE API. See [api](../howto/api.md) to view the delete api.
```suggestion
While not mandatory, the client may issue a delete of the notification via a DELETE method. See [api](../howto/api.md) to view the delete api.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/notifications.md
> +Deleting a notification ID will clean up resources in the notifier quicker. Otherwise the notifier will wait a pre-determined length of time before clearing delivered notifications from its database.
```suggestion
Deleting a notification ID will clean up resources in the notifier quicker. Otherwise the notifier will wait a predetermined length of time before clearing delivered notifications from its database.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/notifications.md
> +If the notifier's configuration specifies "direct=true" for AMQP notifications will be delivered directly to the configured exchange.
```suggestion
If the notifier's configuration specifies `direct: true` for AMQP, notifications will be delivered directly to the configured exchange.
```

Out config is yaml, use yaml constructs when talking about it instead of inventing syntax.

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/notifications.md
> +When "direct=true" the "rollup" property maybe set to instruct the notifier to send a max number of notifications in a single AMQP message. This allows a balance between size of the message and numbe
```suggestion
When `direct` is set, the `rollup` property may be set to instruct the notifier to send a max number of notifications in a single AMQP message. This allows a balance between size of the message and number of messages delivered to the queue.
```

If you can't replace "maybe" with "perhaps", you mean "may be".

2020-09-10 19:36 UTC, hdonnay commented on Documentation/concepts/notifications.md
> +When this environment variable is discovered the notifier will begin sending fake notifications to the configured delivery mechanism every "poll_interval" interval. This provides an easy way to imple
```suggestion
When this environment variable is set, the notifier will begin sending fake notifications to the configured delivery mechanism every "poll_interval" interval. This provides an easy way to implement and test new or existing deliverers.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/contribution/commit_style.md
> +The Clair and ClairCore project utilize well structured commits.
```suggestion
The Clair project utilizes well structured commits to keep the history useful and help with release automation.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/contribution/commit_style.md
> +Subject is a short and concise summary of the change the commit is introducing.
```suggestion
Subject is a short and concise summary of the change the commit is introducing. It should be a sentence fragment without starting capitalization and ending punctuation and limited to about 60 characters, to allow for the scope prefix and decoration in the git log.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/reference.md
> +# Reference
???

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/api.md
> +See [Api Reference](./reference/api.md) for a markdown rendered api reference.
```suggestion
See [API Reference](./reference/api.md) for a markdown rendered API reference.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/api.md
> +ClairV4 provides its API defintion via an OpenAPI specification. You can view our OpenAPI spec [here](https://raw.githubusercontent.com/quay/clair/development-4.0/openapi.yaml)
```suggestion
Clair provides its API definition via an OpenAPI specification. You can view our OpenAPI spec [here](https://raw.githubusercontent.com/quay/clair/development-4.0/openapi.yaml)
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/api.md
> +* Validating data returned from ClairV4
```suggestion
* Validating data returned from Clair
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/api.md
> +* Importing into a rest client such as [PostMan](https://learning.postman.com/docs/integrations/available-integrations/working-with-openAPI/)
```suggestion
* Importing into a rest client such as [Postman](https://learning.postman.com/docs/integrations/available-integrations/working-with-openAPI/)
```

Postman isn't capped like that.

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/api.md
> +See [Testing ClairV4](./testing.md) to learn how the local dev tooling starts a local swagger editor. This is handy for making changes to the spec in real time.
```suggestion
See [Testing Clair](./testing.md) to learn how the local dev tooling starts a local swagger editor. This is handy for making changes to the spec in real time.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +# Deploying ClairV4
```suggestion
# Deploying Clair
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +ClairV4 was designed with flexible deployment architectures in mind. The operator is free to choose a deployment model which scales to their use cases.
```suggestion
Clair v4 was designed with flexible deployment architectures in mind. The operator is free to choose a deployment model which scales to their use cases.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +Before jumping directly into the models its important to note that ClairV4 is capable of using a single configuration file across all node types. This design decision makes it very easy to deploy on
```suggestion
Before jumping directly into the models its important to note that Clair is designed to use a single configuration file across all node types. This design decision makes it very easy to deploy on systems like Kubernetes and OpenShift.
```

OpenShift is inter-capped in its documentation.

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +In a combined deployment all node types run on in a single Clair process. This is by far the easiest deployment model to configure as it involves the least moving parts.
```suggestion
In a combined deployment, all the Clair processes run in a single OS process. This is by far the easiest deployment model to configure as it involves the least moving parts. 
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +A load balancer is still recommended if you plan on performing TLS termination. Typically this will be a Openshift route or a Kubernetes ingress.
```suggestion
A load balancer is still recommended if you plan on performing TLS termination. Typically this will be a OpenShift route or a Kubernetes ingress.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +In the above diagram Clair is running in combo mode and talking to a single database. To configure this model you will provide all node types the same database and start clair in **combo** mode.
```suggestion
In the above diagram, Clair is running in combo mode and talking to a single database. To configure this model you will provide all node types the same database and start Clair in **combo** mode.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +In this mode any configuration informing Clair how to talk to other nodes is ignored, it is not needed as all api communication is done in process.
```suggestion
In this mode, any configuration informing Clair how to talk to other nodes is ignored, it is not needed as all intra-process communication is done directly.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +For added flexibility its also supported to split the databases while in combo mode.
```suggestion
For added flexibility, it's also supported to split the databases while in combo mode.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +In the above diagram Clair is running in combo mode but database load is split between multiple databases. Since Clair is conceptually a set of micro-services, nodes communicate over API and do not s
```suggestion
In the above diagram, Clair is running in combo mode but database load is split between multiple databases. Since Clair is conceptually a set of micro-services, its processes do not share database tables even when combined into the same OS process.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +# Deploying ClairV4
In general in this doc, I'm removing "node" (easily confused with k8s nodes), referring to Clair's logical services as "processes" and always adding the "OS" qualifier when talking about a linux process.

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +To configure this model you would provide each node type it's own "connstring" in the configuration.
```suggestion
To configure this model, you would provide each process its own "connstring" in the configuration. 
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +If your application needs to asymetrically scale or you expect high load you may want to consider a distributed deployment.
```suggestion
If your application needs to asymmetrically scale or you expect high load you may want to consider a distributed deployment.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +In a distributed deployment each Clair node type runs in its own process. Typically this will be a Kubernetes\Openshift deployment or your public cloud of choice's auto scaling mechanism.
```suggestion
In a distributed deployment, each Clair process runs in its own OS process. Typically this will be a Kubernetes or OpenShift Pod.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +A load balancer **must** be setup in this deployment model. The load balancer will route traffic between Clair nodes along with routing API requests via [path based routing](https://devcentral.f5.com
```suggestion
A load balancer **must** be setup in this deployment model. The load balancer will route traffic between Clair nodes along with routing API requests via [path based routing](https://devcentral.f5.com/s/articles/the-three-http-routing-patterns-you-should-know-30764) to the correct services. In a Kubernetes or OpenShift deployment this is usually handled with the Service and Routes abstractions. If deploying on bare metal, a load balancer will need to be configured appropriately. 
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +In the above diagram a load balancer is configured to route traffic coming from the client to the correct service. This routing is path based routing and requires a layer 7 load balancer. Traefik, Ng
```suggestion
In the above diagram, a load balancer is configured to route traffic coming from the client to the correct service. This routing is path based routing and requires a layer 7 load balancer. Traefik, Nginx, and HAProxy are all capable of this. As mentioned above, this functionality is native to OpenShift and Kubernetes.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +In this configuration you'd supply each node type with their own database conn string and inform each node type how to contact their dependent services. Each node will need to have it's mode CLI flag
```suggestion
In this configuration, you'd supply each process with database connection strings and addresses for their dependent services. Each OS process will need to have its "mode" CLI flag or environment variable set to the appropriate value. 
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +Keep in mind you do not need a config file per node type. You may provide each node the same config and each node will configure itself correctly, only using the values necessary for their configured
```suggestion
Keep in mind a config file per process is not need. Processes only use the values necessary for their configured mode.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +Currently ClairV4 punts TLS termination to the load balancing infrastucture. This is a design choice due to the ubiquity of Kubernetes and Openshift infrastructure providing this facility. ClairV4 re
```suggestion
Currently Clair offloads TLS termination to the load balancing infrastructure. This design choice is due to the ubiquity of Kubernetes and OpenShift infrastructure already providing this facility.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +When the loadbalancer encounters a particular path prefix it must send those request to the correct set of ClairV4 nodes.
```suggestion
When the load balancer encounters a particular path prefix it must send those request to the correct set of Clair nodes. 
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/deployment.md
> +For example this is how we configure Traefik in our local development environment.
```suggestion
For example, this is how we configure Traefik in our local development environment:
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_clair.md
> +# Getting Started With ClairV4
```suggestion
# Getting Clair
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_clair.md
> +All of the source code needed to build clair is packaged as an archive and
```suggestion
All of the source code needed to build Clair is packaged as an archive and
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_clair.md
> +##
trailing something

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_clair.md
> +and version tags are built from the corresponding release.
This isn't true, but probably will be in the near future

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +# Getting Started With ClairV4
```suggestion
# Getting Started With Clair
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +# Getting Started With ClairV4
This file duplicates a large chunk of the previous one.

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +The easiest way to get ClairV4 up and running for test purposes is to use our [local dev environment](./testing.md)
```suggestion
The easiest way to get Clair up and running for test purposes is to use our [local dev environment](./testing.md)
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +## ClairV4 Modes
```suggestion
## Modes
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +ClairV4 can run in several modes. [Indexer](../reference/indexer.md), [matcher](../reference/matcher.md), [notifier](../reference/notifier.md) or combo mode. In combo mode all of the mentioned node t
```suggestion
Clair can run in several modes. [Indexer](../reference/indexer.md), [matcher](../reference/matcher.md), [notifier](../reference/notifier.md) or combo mode. In combo mode, everything runs in a single OS process. 
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +If you are just starting with ClairV4 you will most likely want to continue with combo mode and venture out to a distributed deployment once acquainted.
```suggestion
If you are just starting with Clair you will most likely want to start with combo mode and venture out to a distributed deployment once acquainted. 
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +ClairV4 uses Postgres for its data persistence. Migrations are supported so you should only need to point ClairV4 to a fresh database and have it do the setup for you.
```suggestion
Clair uses PostgreSQL for its data persistence. Migrations are supported so you should only need to point Clair to a fresh database and have it do the setup for you.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +We will assume you have setup a postgres database its reachable with the following connection string:
```suggestion
We will assume you have setup a postgres database it's reachable with the following connection string:
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +## Starting ClairV4 In Combo Mode
```suggestion
## Starting Clair In Combo Mode
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +*You may need to configure [docker](https://docs.docker.com/network/) or [podman](https://podman.io/getting-started/network.html) networking if you are utilizing containers. This is out of scope for
```suggestion
*You may need to configure [docker](https://docs.docker.com/network/) or [podman](https://podman.io/getting-started/network.html) networking if you are utilizing containers. This is out of scope for this how-to.*
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +At this point you either have built ClairV4 from source or you have the ClairV4 container pulled. In either case we will assume that the clair-db hostname can be resolved to your postgres database.
```suggestion
At this point, you should either have built Clair from source or have pulled the container. In either case, we will assume that the `clair-db` hostname will resolve to your postgres database. 
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +A basic config for combo mode can be found [here](https://github.com/quay/clair/blob/development-4.0/config.yaml.sample). Make sure to edit this config with your database settings and flip "migration
```suggestion
A basic config for combo mode can be found [here](https://github.com/quay/clair/blob/development-4.0/config.yaml.sample). Make sure to edit this config with your database settings and set "migrations" to `true` for all mode stanzas. In this basic combo mode, all "connstring" fields should point to the same database and any *_addr fields are simply ignored. For more details see the [config reference](../reference/config.md) and [deployment models](./deployment.md)
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +* a mode cli flag or CLAIR_MODE env variable telling what node type this Clair will run as.
```suggestion
* The `mode` flag or `CLAIR_MODE` environment variable specifying what mode this instance will run in.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +* a conf cli flag or CLAIR_CONF env variable telling where Clair can find its configuration.
```suggestion
* The `conf` flag or `CLAIR_CONF` environment variable specifying where Clair can find its configuration.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +* a structured yaml config providing the bulk of Clair's configuration.
```suggestion
* A yaml document providing Clair's configuration.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +If you are running a container you can can [mount](https://docs.docker.com/storage/volumes/) a clair config to any readable path you like and set the env vars to:
```suggestion
If you are running a container, you can can [mount](https://docs.docker.com/storage/volumes/) a Clair config and set the `CLAIR_CONF` environment variable to the corresponding path.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +If you are running Clair from a built binary its likely easiest to issue the following command line
```suggestion
If you are running a Clair binary directly, its likely easiest to use the command line.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +The simplest way to submit a manifest to your running Clair is utilizing [clairctl](../reference/clairctl.md). This is a CLI tool capable of grabbing images from public repositories and and submittin
```suggestion
The simplest way to submit a manifest to your running Clair is utilizing [clairctl](../reference/clairctl.md). This is a CLI tool capable of grabbing image manifests from public repositories and and submitting them for analysis. 
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +This CLI will be in your ClairV4 container and can also be installed by running the following command:
```suggestion
The command will be in the Clair container, but can also be installed locally by running the following command:
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +$ clairctl --host {net_address_of_clair} report {image:tag}
```suggestion
$ clairctl --host ${net_address_of_clair} report ${image_tag}
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +By default the tool will look for clair at `localhost:6060` (our local development address) but you may change this.
```suggestion
By default, `clairctl` will look for Clair at `localhost:6060`.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +If all things look good you should see some output like the following informting you of vulnerabilities affecting the supplied image.
```suggestion
If everything is configured correctly, you should see some output like the following informing you of vulnerabilities affecting the supplied image.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +## Whats Next
```suggestion
## What's Next
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +Now that you see the basic usage of ClairV4 you can checkout our [deployment models](./deployment.md) to learn different ways of deploing ClairV4.
```suggestion
Now that you see the basic usage of Clair, you can checkout our [deployment models](./deployment.md) to learn different ways of deploying.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/getting_started.md
> +You may also be curious about how clairctl did that work. Check out out [api definition](./api.md) to understand how an application would interact with ClairV4 without a client.
```suggestion
You may also be curious about how `clairctl` did that work. Check out our [API definition](./api.md) to understand how an application interacts with Clair.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/testing.md
> +# Testing ClairV4
```suggestion
# Testing Clair
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/testing.md
> +We provide dev tooling in order to quickly get a fully configured ClairV4 and Quay local dev environment stood up. This environment can be used to test ClairV4 and also develop against.
```suggestion
We provide dev tooling in order to quickly get a fully configured Clair and Quay environment stood up locally. This environment can be used to test and develop Clair.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/testing.md
> +It's very likely you workstation already has make on it. Give it a try!
```suggestion
Make is used to stand up the the local dev environment. 
Make is readily available in just about every package manager you can think of.
It's very likely your workstation already has make on it.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/testing.md
> +Currently our local dev tooling is supported by docker and docker-compose. We are making strides to provide a podman native local dev environment but we are not quite there yet.
```suggestion
Currently our local dev tooling is supported by docker and docker-compose. We are making strides to provide a podman native local dev environment but we are not quite there yet.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/testing.md
> +Docker version 19.03.11 and docker-compose version 1.25.4 are confirmed working. Assumption is most version wil not have an issue running the local dev tooling.
```suggestion
Docker version 19.03.11 and docker-compose version 1.25.4 are confirmed working. Our assumption is most recent versions will not have an issue running the local dev tooling.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/testing.md
> +### Go Tool Chain
```suggestion
### Go Toolchain
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/testing.md
> +Go v1.13 or higher is required to create a local vendor folder.
```suggestion
Go v1.13 or higher is required.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/testing.md
> +After the local development environment successfully starts the following infrastructure is available to you..
```suggestion
After the local development environment successfully starts, the following infrastructure is available to you:
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/testing.md
> +As mentioned above Quay is present at `localhost:8080`. You may navigate to this address and create a account. Creating an account named `admin` will ensure you are a super user. An email is required
```suggestion
As mentioned above ,Quay is present at `localhost:8080`. You may navigate to this address and create a account. Creating an account named `admin` will ensure you are a super user. An email is required, but is not validated.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/testing.md
> +Once inside you will create an organization named "clairv4-org". Currently Quay has to explicitly enable ClairV4 security scanning. It does this via a organization whitelist. As you can guess, "clair
```suggestion
Once inside, you will create an organization named "clairv4-org". Currently Quay has to explicitly enable Clair v4 security scanning, which is done via an organization allowlist. "Clairv4-org" is preconfigured in our local dev configuration.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/testing.md
> +The easiest way to push to Quay would be using podman.
```suggestion
The easiest way to push to Quay is using podman:
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/testing.md
> +Docker pushes is possible however you will need to add "localhost:8080" as an insecure repository. See [Insecure Repository](https://docs.docker.com/registry/insecure/)
```suggestion
Using docker to push is possible, however you will need to add "localhost:8080" as an insecure repository. See [Insecure Repository](https://docs.docker.com/registry/insecure/)
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/testing.md
> +`./local-dev/quay/config.yaml` and `./local-dev/clair.yaml`
```suggestion
You may want to play with either Clair or Quay's configuration. 
If so, the configuration files can be found inside the repository at
`local-dev/quay/config.yaml` and `local-dev/clair.yaml`.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/testing.md
> +Any changes to the configs will require a restart of the local dev service. Take a lookat the `./Makefile` for the various restart targets.
```suggestion
Any changes to the configs will require a restart of the relevant service. Take a look at the `Makefile` for the various restart targets.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/howto/testing.md
> +The most common issue encountered when standing up the dev environment is port conflicats. You must make sure that you do not have any other processes listening on any of the ports outlined above.
```suggestion
The most common issue encountered when standing up the dev environment is port conflicts. Make sure that you do not have any other processes listening on any of the ports outlined above.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/reference/clairctl.md
> +`clairctl` is a command line tool for working with ClairV4.
```suggestion
`clairctl` is a command line tool for working with Clair.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/reference/clairctl.md
> +This CLI is capable of generating manifests from most public registires (docker, quay.io, redhat container catalog) and submitting them for analysis to a running ClairV4.
```suggestion
This CLI is capable of generating manifests from most public registries (dockerhub, quay.io, Red Hat Container Catalog) and submitting them for analysis to a running Clair.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/reference/clairctl.md
> +   clairctl - A new cli application
Ah whoops. Will make a note to fix the online help in the tool.

2020-09-10 19:36 UTC, hdonnay commented on Documentation/reference/indexer.md
> +When ClairV4 is running in Indexer mode its is responsible for receiving Manifests and generating IndexReports. An IndexReport is an intermediate representation of a container's content and is used t
```suggestion
When Clair is running in Indexer mode, it is responsible for receiving Manifests and generating IndexReports. An IndexReport is an intermediate representation of a manifest's content and is used to discover vulnerabilities.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/reference/matcher.md
> +When ClairV4 is running in Matcher mode its is responsible for receiving IndexReports and generating VulnerabilityReports. A VulnerabilityReport describes the contents of a container and any vulnerab
```suggestion
When Clair is running in Matcher mode it is responsible for receiving IndexReports and generating VulnerabilityReports. A VulnerabilityReport describes the contents of a manifest and any vulnerabilities affecting it.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/reference/notifier.md
> +When ClairV4 is running in Notifier mode its is responsible for generating notifications when new vulnerabilities affecting an indexed manifest enter the system. The notifier will either send a notif
```suggestion
When ClairV4 is running in Notifier mode its is responsible for generating notifications when new vulnerabilities affecting an indexed manifest enter the system. The notifier will either send a notification to a message borker (AMPQ, STOMP) or fire a webhook at a configurable target.
```
```suggestion
When Clair is running in Notifier mode, it is responsible for generating notifications when new vulnerabilities affecting a previously indexed manifest enters the system. The notifier will send notifications via the configured mechanisms.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/whatis.md
> +# What is ClairV4
```suggestion
# What is Clair
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/whatis.md
> +ClairV4 is an application for parsing container contents and reporting any vulnerabilities affecting the image. These actions happen via static analysis and not during container runtime.
```suggestion
Clair is an application for parsing image contents and reporting vulnerabilities affecting the contents. This is done via static analysis and not at runtime.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/whatis.md
> +ClairV4 utilizes the [ClairCore](https://quay.github.io/claircore/) library as its engine for extracing image contents and reporting vulnerabilities. At a high level you can consider ClairV4 a servic
```suggestion
Clair v4 utilizes the [ClairCore](https://quay.github.io/claircore/) library as its engine for examining contents and reporting vulnerabilities. At a high level you can consider Clair a service wrapper to the functionality provided in the ClairCore library. 
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/whatis.md
> +The above diagram expresses the separation of concerns between ClairV4 and the ClairCore library. Most development involving new distrubtion, vulnerability analysis, and container indexing will occur
```suggestion
The above diagram expresses the separation of concerns between Clair and the ClairCore library. Most development involving new distributions, vulnerability sources, and layer indexing will occur in ClairCore.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/whatis.md
> +## How ClairV4 Works
```suggestion
## How Clair Works
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/whatis.md
> +ClairV4's container analysis is broken into three distinct parts.
```suggestion
Clair's analysis is broken into three distinct parts.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/whatis.md
> +Indexing is the act of submitting a Manifest to ClairV4. On receipt ClairV4 will fetch all the layers, scan each layer for contents, and create an intermediate representation of the contents called a
> Indexing is the act of submitting a Manifest to ClairV4.

This is inaccurate.

```suggestion
Indexing starts with submitting a Manifest to Clair. On receipt, Clair will fetch layers, scan their contents, and return an intermediate representation called an IndexReport. 
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/whatis.md
> +Manifests are treated as content-addressable containeers. A manifest's hash will always represent the same content and ClairV4 exploits this fact, not performing duplicate work unless necessary.
```suggestion
Manifests are Clair's representation of a container image. Clair leverages the fact that OCI Manifests and Layers are content-addressed to reduce duplicated work.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/whatis.md
> +Once a Manifest is indexed the IndxReport is persisted for later retrieval.
```suggestion
Once a Manifest is indexed, the IndexReport is persisted for later retrieval. 
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/whatis.md
> +The matcher takes care to not cache any datat for too long. ClairV4 is continually indexing new security data and a request to the matcher will always provide you with the most up to date vulnerabili
```suggestion
Clair is continually ingesting new security data and a request to the matcher will always provide you with the most up to date vulnerability analysis of an IndexReport.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/whatis.md
> +Matching is the act of taking an IndexReport and discovering vulnerabilties affecting the container the report represents.
```suggestion
Matching is taking an IndexReport and correlating vulnerabilities affecting the manifest the report represents. 
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/whatis.md
> +*how we implement indexing and matching in detail is covered in [ClairCore's](https://quay.github.io/claircore/) documentation*
```suggestion
*How we implement indexing and matching in detail is covered in [ClairCore's](https://quay.github.io/claircore/) documentation.*
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/whatis.md
> +ClairV4 implements a notification service.
```suggestion
Clair implements a notification service. 
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/whatis.md
> +When new vulnerabilities are discovered the notifier service will determine if these vulnerabilities affect any indexed Manifests. The notifier will then fire a web hook or deliver a notification to
```suggestion
When new vulnerabilities are discovered, the notifier service will determine if these vulnerabilities affect any indexed Manifests. The notifier will then take action according to its configuration.
```

2020-09-10 19:36 UTC, hdonnay commented on Documentation/whatis.md
> +At this point you'll probably want to check out [Getting Started With ClairV4](./howto/getting_started.md)
```suggestion
At this point you'll probably want to check out [Getting Started With Clair](./howto/getting_started.md).
```

2020-09-10 19:39 UTC, ldelossa commented on Documentation/concepts/authentication.md
> +# Authentication
I think this got a little junked up with "mv" cmd. this should have been split into "operation" and "authentication" two separate files. You agree?

2020-09-10 19:42 UTC, ldelossa commented on Documentation/concepts/indexing.md
> +## Summary
Summary == Conclusion, no? I guess you expect a summary at the start of the doc?

2020-09-10 19:45 UTC, ldelossa commented on Documentation/concepts/notifications.md
> +When the notifier becomes aware of new vulnerabilities affecting an index manifest it will inform the client of the change. The client will receive a single notification expressing the **most servere
Nope, that mechanism holds true for any delivery method. The difference of delivery methods only include "whether notifications are delivered directly to a queue, or a callback schema is delivered to a queue"

2020-09-10 19:46 UTC, ldelossa commented on Documentation/concepts/notifications.md
> +  "callback": {url_to_notifications}
willing to change, but did you make sure rendering works? a lot of time angle brackets get confused with html even in quotes with Markdown.

2020-09-10 19:46 UTC, ldelossa commented on Documentation/concepts/notifications.md
> +```go
it still looks better with *some* kind of syntax highlighting.

2020-09-10 19:51 UTC, ldelossa commented on Documentation/howto/getting_clair.md
> +and version tags are built from the corresponding release.
Yeah I did a little bit of forward documenting here. Leave it?

2020-09-10 19:53 UTC, ldelossa commented on Documentation/howto/getting_started.md
> +# Getting Started With ClairV4
I am pretty sure I meant to remove "Getting Clair"... but I am not sure at this point. You think we should just remove "Getting Clair" this is a full tutorial.

2020-09-14 18:46 UTC, hdonnay commented on Documentation/concepts/notifications.md
> +  "callback": {url_to_notifications}
Oh, I didn't check that, I assumed it being in a literal means it wouldn't get interpreted

2020-09-14 18:54 UTC, hdonnay approved these changes
SGTM

2020-09-14 18:56 UTC, ldelossa commented on Documentation/concepts/notifications.md
> +  "callback": {url_to_notifications}
yup, just checked with 
```
Here is a string "<help>"
```

renders to: Here is a string "" 

thinks its a custom tag :(

2020-09-14 18:56 UTC, merged