Readiness swap
quay/clair pull request #1161
Opened 2021-01-22 20:07 UTC by hdonnay

This change (based on #1111) has the http server start serving requests immediately, and start serving the API after initialization is done.

2021-01-25 16:05 UTC, hdonnay commented
Going to rework claircore's init and then circle back to this.

2021-01-25 16:13 UTC, ldelossa commented
how does this PR compare with https://github.com/quay/claircore/pull/300 

doesn't #300 obsolete this?

2021-01-25 19:46 UTC, hdonnay commented
We'll still need to do something in clair's http layers to make use of the information exposed in that change.

2021-01-25 22:36 UTC, ldelossa commented
Gotchya, was expecting a new PR, but doesn't matter if this one used.

2021-02-02 20:59 UTC, alecmerdler commented
@hdonnay Let me know if you need help testing this. This is going to speed up TNG Operator's reconciliation of `QuayRegistry` objects so much faster (Clair updaters take ~3 min to complete, blocking Quay startup).

2021-03-09 19:30 UTC, hdonnay commented
This has been reworked and rebased in face of claircore changes.

2021-03-12 20:30 UTC, ldelossa requested changes
Possible to write a integration test for this in some way? Ensuring you see the appropriate status codes change at the appropriate times?

2021-03-18 20:04 UTC, alecmerdler commented
@hdonnay Would love to see this merged. Is there any way I can help test?

2021-03-18 20:06 UTC, ldelossa commented
From my point of view, it just needs a test that confirms the http status flips correctly when initialized

2021-03-19 19:35 UTC, hdonnay commented
I'll jump on a test for the handler. To test it live, you should just need to run it with no updaters (`$.updaters.sets = []`) against an empty database.

2021-03-23 14:49 UTC, ldelossa submitted a review, later dismissed
@hdonnay approved, needs rebase, ping me when done for re-ack.

2021-03-23 14:56 UTC, ldelossa approved these changes

2021-03-23 15:00 UTC, merged