contrib: First wipe anything that might be left before starting clair indexers
quay/clair pull request #1600
Opened 2022-07-08 18:21 UTC by crozzy

We have observed that the postStart command is not consistently
wiping the /tmp dir as it appears like there is a race
condition as the PVC is not guaranteed to be mounted when it is
run.

Signed-off-by: crozzy <joseph.crosland@gmail.com>

2022-07-15 17:28 UTC, hdonnay requested changes

2022-07-15 17:28 UTC, hdonnay commented on contrib/openshift/manifests/manifests.yaml
> +                - rm -rf /tmp/sha* /tmp/fetch.* && clair
```suggestion
                - rm -rf /tmp/sha* /tmp/fetch.* && exec clair
```
Adding `exec` means `clair` will take over the shell process and not have it hanging around.

2022-07-28 18:31 UTC, hdonnay commented on contrib/openshift/manifests/manifests.yaml
>                    value: '/etc/clair/config.yaml'
@prr approve

2022-07-28 18:32 UTC, hdonnay submitted a review, later dismissed
LGTM

2022-07-28 19:56 UTC, crozzy commented
merging with superpowers as conflictless rebase

2022-07-28 19:56 UTC, merged