cicd: Moved tests from config ci module to nightly ci with ppc64le support
quay/clair pull request #1780
Opened 2023-06-15 09:04 UTC by raja-0940

Moved tests from config ci module to nightly ci with ppc64le support

2023-06-15 16:05 UTC, hdonnay requested changes
I don't understand what this is doing that it doesn't already.

What's the point, here?

2023-06-15 16:31 UTC, raja-0940 commented
As part of [PROJQUAY-5377](https://issues.redhat.com/browse/PROJQUAY-5377), Worked on adding ppc64le support to the tests for the config ci module of the Clair.

2023-06-15 20:54 UTC, hdonnay commented
Sure, but it already does that. What does this addition do?

2023-06-16 03:33 UTC, yussufsh commented
If I am not wrong @raja-0940  is adding "Config CI" tests as part of "Nightly CI" for arch-specific runs. Currently, it's just integration tests running for ppc64le.

2023-06-21 17:12 UTC, hdonnay commented
That's not the case. The tests already run for the `github.com/quay/clair/config` module. So what does this addition do that the existing step doesn't?

2023-06-23 14:03 UTC, yussufsh commented on .github/workflows/config-ci.yml
> +          -tags tests \
Is this tags option needed?

2023-07-03 18:28 UTC, hdonnay commented
Will close shortly if there's no explanation on how this doesn't duplicate existing functionality.

2023-07-04 13:10 UTC, mpkpersistent commented
Hi @hdonnay,
The code changes are targeted to add ppc64le arch support to the config-ci module.
Pl refer https://issues.redhat.com/browse/PROJQUAY-5377 for more details.

2023-07-05 16:39 UTC, hdonnay commented
For the fourth time: the `github.com/quay/clair/config` module has the tests run on all architectures in the existing Nightly CI. I'll close this tomorrow if there's no explanation as to why this is needed.

2023-07-06 12:56 UTC, closed without merging

2023-07-06 12:57 UTC, raja-0940 commented
Had a group discussion with Hank to explain that config module is not having the ppc64le arch support, hence we have created the PR. 

But PR got rejected citing reason that "github.com/quay/clair/config module has the tests run on all architectures in the existing Nightly CI."