cicd: openshift CI
quay/clair pull request #2083
Opened 2024-06-28 21:52 UTC by hdonnay

This retools the Makefile and Dockerfile to use a buildkit backend directly in an attempt to stop needing to write a Dockerfile and scripts that only use the intersection of `podman` and `docker` features.

TODO:
- [ ] Documentation updates
- [ ] Port the GitHub Actions CI to use the Makefile where appropriate.

2024-06-28 23:17 UTC, hdonnay commented
Currently failing due to extremely annoying AppSRE footguns, will pick up later.

2024-07-02 15:16 UTC, hdonnay commented
cc @Marcusk19 @bcaton85

There might be some Quay build concerns, so FYI.

2024-07-11 18:05 UTC, crozzy requested changes

2024-07-11 18:05 UTC, crozzy commented on etc/config.mk
> +# This should be able to be interpreted accorting to gitrevisions(7) and a
nit: spelling

2024-07-11 18:05 UTC, crozzy commented on etc/config.mk
> +$(error 'docker' must not be defined as empty)
Do these errors get surfaced to the user? If so should we mention that 'podman' will suffice too?

2024-07-11 18:05 UTC, crozzy commented on etc/container.mk
> +buildctl += --export-cache type=gha,mode=max
huh, special mode for gh actions, nice

2024-07-11 19:38 UTC, hdonnay commented on etc/config.mk
> +$(error 'docker' must not be defined as empty)
They do, I'll make that change

2024-07-15 17:44 UTC, hdonnay commented
I guess ignore the devshift failure, despite it being the motivator of this whole exercise?

2024-07-15 18:52 UTC, hdonnay commented
[test]

2024-07-16 18:00 UTC, crozzy approved these changes, later dismissed
SGTM

2024-07-16 18:12 UTC, crozzy approved these changes

2024-07-16 18:12 UTC, hdonnay commented
/fast-forward

2024-07-16 18:12 UTC, merged