Verify database state with retry
quay/clair pull request #252
Opened 2016-09-29 14:29 UTC by ScorpioCPH

As mentioned in README

`Docker Compose may start Clair before Postgres which will raise an error. If this error is raised, manually execute docker start clair_clair.` 

so I add retry in verify database to avoid exiting.

2016-09-29 14:31 UTC, ScorpioCPH commented
@Quentin-M, please review my PR, thanks!

2017-08-14 21:45 UTC, jzelinskie requested changes
I think this is a fair idea, but I think that 60s is probably way too long and that we should be using exponential backoff. You can use `github.com/coreos/pkg/timeutil`'s ExpBackOff function for this.

2017-08-14 21:45 UTC, jzelinskie commented on database/pgsql/pgsql.go
> +				time.Sleep(2 * time.Second)
this should be exponential backoff

2017-08-14 21:45 UTC, jzelinskie commented on database/pgsql/pgsql.go
> +	ch := make(chan int, 1)
`make(chan struct{})`

2017-12-13 19:23 UTC, ajgreenb commented
@jzelinskie I think this PR can now be closed?

2017-12-13 19:50 UTC, ScorpioCPH commented
@ajgreenb Sure! Sorry for the late response.

2017-12-13 19:50 UTC, closed without merging