Add flag to notify when the db is done updating
quay/clair pull request #253
Opened 2016-09-30 08:00 UTC by AndreeaDora

This uses a flag that will notify when the updating of the db is done so an image could be tested only after all the vulnerabilities are added to the db.

2016-11-01 10:54 UTC, soninob commented
👍 
Can this be merged?
It is important to be notified when the update is done.
Looking forward seeing it merge :-)

2016-11-03 14:36 UTC, Quentin-M commented on updater/updater.go
> +			DbFinishUpdate = false
This is unfortunately far from enough to determine whether the initial update succeeded or not. First of all, your else block will be executed when it is not yet time to update and set the update status as unfinished, this does not really make sense. Also,
- Consider the case in which you have multiple Clair instances running and only one of them realizes the updates.
- Consider the case in which Clair is restarted.

2016-11-03 14:37 UTC, Quentin-M requested changes

2016-11-03 14:37 UTC, Quentin-M commented on updater/updater.go
> +			DbFinishUpdate = false
This is unfortunately far from enough to determine whether the initial update succeeded or not. First of all, your else block will be executed when it is not yet time to update and set the update status as unfinished, this does not really make sense. Also,
- Consider the case in which you have multiple Clair instances running and only one of them realizes the updates.
- Consider the case in which Clair is restarted.

2016-11-04 08:23 UTC, AndreeaDora commented on updater/updater.go
> +			DbFinishUpdate = false
@Quentin-M Thank you for your feedback. This code determines if the update finished or not. As you can see in the logs the variable is set to false when the DB update is completed. If Clair is restarted same checks will be done. I will consider the case where we have multiple Clair instances running and only one of them  realizes the updates.

2016-11-11 14:27 UTC, Quentin-M commented on api/v1/routes.go
> +		writeResponse(w, r, http.StatusNotFound, LayerEnvelope{Error: & Error{"DB is being updated so no query to it can be done"}})
The message could be clearer. Something like: `The initial vulnerability update has not finished yet, therefore this API call is currently unavailable. Please try again later`. Also, the error code should probably be 503.

2016-11-11 14:28 UTC, Quentin-M commented on updater/updater.go
> +			DbFinishUpdate = false
@AndreeaDora You may make use of the available `firstUpdate` variable. While not entirely safe (the updater doesn't keep its distributed state in a specialized service such as etcd), it is better already.

2016-11-16 08:19 UTC, AndreeaDora commented on api/v1/routes.go
> +		writeResponse(w, r, http.StatusNotFound, LayerEnvelope{Error: & Error{"DB is being updated so no query to it can be done"}})
@Quentin-M I added the changes that you requested on the error code and message.

2016-11-16 08:32 UTC, AndreeaDora commented on updater/updater.go
> +			DbFinishUpdate = false
@Quentin-M The `firstUpdate` variable can not be used to determine when the update is done, that is the reason I used another variable that will change the value depending on the stage of the update.

2017-04-07 09:16 UTC, tobilg commented
What's the status on this? Thanks!

2017-07-09 07:22 UTC, yixingjia commented
This is a very valuable feature that greatly improve the usability.

It will be great if this can be include in Clair earlier. 

Our project(https://github.com/vmware/harbor) also integrate Clair  and we need this information when Vulnerability db has been updated.

2017-08-07 09:17 UTC, soninob commented
any updates on this?

2018-09-26 22:11 UTC, jzelinskie commented
The v3 API now contains a timestamp for the last update in its responses. I don't think this PR is necessary anymore.

Thanks for all the work.

2018-09-26 22:11 UTC, closed without merging