skip TLS check for detecting layer data
quay/clair pull request #256
Opened 2016-10-24 03:27 UTC by supereagle

This skips TLS check for detecting layer data from Server 
configured with TLS. 

Fixes #251

2016-10-24 03:41 UTC, supereagle commented
@Quentin-M  PTAL. Thanks!

2016-10-24 16:39 UTC, jzelinskie commented
Disabling these checks should be behind a flag if we're going to support it because defaulting to this behavior is dangerous. You _should_ be adding your certificates to the system root (and mounting that into a container).

2016-10-25 06:36 UTC, supereagle commented
@jzelinskie   Thanks for your review and advice.

Yes. Users can avoid this error by adding the certificates. But if the layer data is from several different servers, this way maybe is not so convenient. At the same time, it will restrict the container to run anywhere.

Adding a flag to control TLS check is a good way. I think we can add a flag `Insecure` in the body of `POST Layer` API, as TLS check is only used for detecting layer data in this REST API. Make the users can dynamically control the TLS check by themselves when call this API, and the default is to enable TLS check.

2016-10-27 10:11 UTC, supereagle commented
@jzelinskie  @Quentin-M  Whether we need to add a flag to support disabling this check?

2016-11-11 17:04 UTC, jzelinskie commented
@supereagle I would not be opposed to adding a flag to the binary for testing called `--insecure-tls` that disabled this across the board.

2016-11-27 13:24 UTC, supereagle commented
@jzelinskie  Is the flag `--insecure-tls` just for testing? Why not for production?

2016-12-03 21:34 UTC, jzelinskie commented
@supereagle For TLS to be secure, it needs to use PKI rather than blindly trusting any certificate it sees. People should be able to run Clair without verifying certificates, but if they want run it in that mode, they should be forced to acknowledge that it's insecure.

2016-12-04 06:07 UTC, supereagle commented
@jzelinskie   Thanks.  I will add this flag.

2016-12-19 05:38 UTC, supereagle commented
@jzelinskie  Have added the flag `--insecure-tls`.  PTAL, thanks.

2017-01-06 13:43 UTC, supereagle commented
@jzelinskie  Any comments about the new work in this PR?

2017-01-08 14:59 UTC, jzelinskie commented
I'm not 100% convinced that this API needs enable dynamic toggling of functionality. thoughts @Quentin-M ?

2017-02-24 19:08 UTC, jzelinskie commented
This needs a rebase.
Also follow-up ping @Quentin-M for thoughts

2017-02-24 20:22 UTC, Quentin-M requested changes

2017-02-24 20:22 UTC, Quentin-M commented on cmd/clair/main.go
> +	flagInsecureTLS := flag.Bool("insecure-tls", false, "Disable TLS check when detect the data of layers.")
> Disable TLS server's certificate chain and host name verification when pulling layers

2017-02-24 20:22 UTC, Quentin-M commented on worker/detectors/data.go
> +	insecureTLSLock sync.Mutex
I feel like the mutex is overkill.

2017-02-24 20:22 UTC, Quentin-M commented on worker/detectors/data.go
> +	// insecureTLS controls the TLS check when detect the data of layers, enabled in default.
> insecureTLS controls whether TLS server's certificate chain and host name are verified when pulling layers

2017-02-24 20:22 UTC, Quentin-M commented on worker/detectors/data.go
> +func SetInsecureTLS(insecure bool) {
I would not bother having a function if there is no mutex.

2017-02-24 20:26 UTC, Quentin-M commented
I understand the use-case and would be willing to merge this.
I don't feel like having an API-level toggle is worth at all though, flag is fine, I even thought for a second that a const overwritten at build time would be enough - but other users might actually want to use this.

2017-02-24 22:30 UTC, supereagle commented on worker/detectors/data.go
> +	insecureTLSLock sync.Mutex
OK, I will remove it.

2017-02-25 23:39 UTC, supereagle commented
Too many conflicts while rebasing.  Create another PR #331 .

2017-02-26 04:38 UTC, closed without merging