pgsql: Do not insert entry in Vulnerability_FixedIn_Feature if existing
quay/clair pull request #263
Opened 2016-11-11 18:20 UTC by Quentin-M

Fixes #238

2016-11-11 18:23 UTC, Quentin-M commented
When this PR lands, it should be backported to the stable branch(es).

2016-11-11 19:27 UTC, jzelinskie requested changes

2016-11-11 19:27 UTC, jzelinskie commented on database/pgsql/queries.go
> +		SELECT 'new', id FROM new_fixedinfeature`
Let's change this first value to be a boolean and bind it to a Go variable named "created" at the callsite.

2016-11-11 19:27 UTC, jzelinskie commented
We really need to break the database tests into different functions that describe the scenario they're testing rather than having one giant monolithic function for each method in the interface.

2016-11-12 14:53 UTC, Quentin-M commented
@jzelinskie https://github.com/coreos/clair/issues/264 + https://github.com/coreos/clair/pull/263/commits/ec0aad9b7a4e8021b633f983f2e1d9ef496bf49c. Thank you!

2016-11-13 06:02 UTC, jzelinskie approved these changes

2016-11-13 06:03 UTC, jzelinskie commented
LGTM. I set a reminder to backport these changes on Monday.

2016-11-13 12:25 UTC, merged