added support for detecting multiple namespaces in a layer
quay/clair pull request #394
Opened 2017-05-12 21:37 UTC by KeyboardNerd

created table layer_namespace to store the many to many unique mapping of layers and namespaces
changed v1 api to provide a list of namespaces for each layer
changed namespace detector to use all registered detectors to detect namespaces
updated tests for multiple namespaces

Fixes #150

2017-05-16 20:55 UTC, jzelinskie requested changes
awesome work! mostly just nitpicks

2017-05-16 20:55 UTC, jzelinskie commented on database/models.go
> +
Any reason why you spaced these out like this? Did this pass gofmt?

2017-05-16 20:55 UTC, jzelinskie commented on database/pgsql/layer.go
> +			_, err := tx.Exec(insertLayerNamespace, layer.ID, nsid)
This could all be done with one insert rather one query per namespace

2017-05-16 20:55 UTC, jzelinskie commented on database/pgsql/queries.go
> +							WHERE lns.layer_id = $1
indentation is a little funky here

2017-05-16 21:09 UTC, KeyboardNerd commented on database/models.go
> +
ah, the broken gofmt in emacs caused this

2017-05-23 19:44 UTC, jzelinskie requested changes

2017-05-23 19:44 UTC, jzelinskie commented on database/pgsql/migrations/00007_add_multiplens.go
> +		ID: 7,
This needs to change to 8.

2017-05-23 19:44 UTC, jzelinskie commented on database/pgsql/layer.go
> +	err = stmt.Close()
If anything fails while iterating over the namespaceIDs, the statement never gets closed. I think it's best to structure it like this instead:
```go
stmt, err := tx.Prepare(insertLayerNamespace)
defer func() {
  err = stmt.Close()
  if err != nil {
    tx.Rollback()
    log.WithFields(log.Fields{"error": err}).Error("failed to close prepared statement")
}()

for nsid := range namespaceIDs {
  ...
}
```

2017-05-23 19:44 UTC, jzelinskie commented on database/pgsql/queries.go
> +							`
let's move this ` to right after the $1

2017-05-23 19:44 UTC, jzelinskie commented on database/pgsql/testdata/data.sql
> +(1, 2, 1),
indent

2017-05-23 19:44 UTC, jzelinskie commented on ext/featurens/driver_test.go
> +					`PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
put the ` on the line above and start PRETTYNAME on a newline right above NAME

2017-05-24 20:54 UTC, jzelinskie requested changes

2017-05-24 20:54 UTC, jzelinskie commented on database/pgsql/layer.go
> +	if err != nil {
move this above the defer or else the defer could possibly cause a nil ptr deference

2017-05-24 21:22 UTC, jzelinskie approved these changes

2017-05-24 21:22 UTC, merged