Clair V3
quay/clair pull request #432
Opened 2017-07-12 21:25 UTC by KeyboardNerd

This is a large Pull Request that will contain a number of chunks. For easier code review, the Clair V3 PR will contains these commits separately.
1. API changes
2. datastore interface changes, database schema
3. datastore implementations with tests
4. ext/ changes
5. worker, updater, notifier changes with tests
6. potentially vendor clean up

2017-07-13 19:42 UTC, jzelinskie requested changes

2017-07-13 19:42 UTC, jzelinskie commented on api/v2/clairpb/clair.proto
> +	// fixed_by only exists when querying features
Can we treat comments like Go ones? Full sentences 80 char lines.

2017-07-13 19:42 UTC, jzelinskie commented on api/v2/clairpb/clair.proto
> +	// all listers and detectors implemented in this clair version
Is this what Clair is built with or configured with?

2017-07-13 19:42 UTC, jzelinskie commented on api/v2/clairpb/clair.proto
>  	string next_token = 2;
maybe rename these 'current_page' and 'next_page'

2017-07-13 19:42 UTC, jzelinskie commented on api/v2/clairpb/clair.proto
>  service AncestryService{
I cannot comment on the line, but we should rename "DeleteNotification" to "MarkNotificationAsRead" and make HTTP DELETE be an implementation detail of the rest gateway

2017-07-13 19:42 UTC, jzelinskie commented on api/v2/rpc.go
> +
any reason you don't defer the rollback here and instead explicitly call it for each branch below?

2017-07-13 19:58 UTC, KeyboardNerd commented on api/v2/rpc.go
> +
I don't think Rollback() should ever be called after Commit() on success.

2017-07-13 20:01 UTC, KeyboardNerd commented on api/v2/clairpb/clair.proto
> +	// all listers and detectors implemented in this clair version
all built-in listers/detectors. The listers and detectors are not configurable now, should I add that to this PR?

2017-07-13 20:54 UTC, jzelinskie commented on api/v2/rpc.go
> +
Rollback() from database/sql actually is safe to do this and is considered an idiomatic pattern to do so. I think it makes sense both ways, though.

2017-07-13 20:54 UTC, jzelinskie commented on api/v2/clairpb/clair.proto
> +	// all listers and detectors implemented in this clair version
Nope, we can do that later, just as long as nothing here prevents us from doing so.

2017-08-03 21:31 UTC, KeyboardNerd commented
I'm using my analyze_local_images/py tools I just wrote to test the APIs, which seems to work properly. I'll do more concurrency tests and the web hook tests.

2017-08-08 19:58 UTC, jzelinskie requested changes
oh boy, here we go

2017-08-08 19:58 UTC, jzelinskie commented on database/models.go
> +// AffectedFeature is used determine whether a namespaced feature is affected.
AffectedFeature is used to determine whether a namespaced feature is affected by a Vulnerability.

2017-08-08 19:58 UTC, jzelinskie commented on api/v2/clairpb/convert.go
> +	// encrypt page numbers
this isn't a particularly useful comment

2017-08-08 19:58 UTC, jzelinskie commented on api/v2/clairpb/convert.go
> +	nextToken, err := dbVuln.Next.Encrypt(paginationKey)
What happens when there is no next page? Is there a special constant for that or does this function need to handle `nil`?

2017-08-08 19:58 UTC, jzelinskie commented on api/v2/clairpb/convert.go
> +	pbOldVuln, err := PagedVulnerableAncestriesFromDatabaseModel(dbOldVuln, paginationKey)
What happens if there is no old vulnerability? Doesn't this need to handle `nil`?

2017-08-08 19:58 UTC, jzelinskie commented on api/v2/rpc.go
> +			return nil, status.Error(codes.NotFound, "requested ancestry \""+ancestry.Name+" \" is not found")
raw string literals will make this easier to read

```go
return nil, status.Error(`requested ancestry "` + ancestry.Name + `" is not found`)
```

2017-08-08 19:58 UTC, jzelinskie commented on api/v2/rpc.go
> +			// ensure every feature is found
```go
// Ensure that every feature can be found.
```

I'd also move this comment to be above `if !fv.Valid` instead of the whole for loop.

2017-08-08 19:58 UTC, jzelinskie commented on database/models.go
> +	// known fixed in version for the vulnerability
full sentences for comments

2017-08-08 19:58 UTC, jzelinskie commented on database/models.go
> +// VulnerabilityWithAffected is an vulnerability with all known affected
**a** vulnerability

2017-08-08 19:58 UTC, jzelinskie commented on database/models.go
> +// Notification is a hook used to notify and give token to user to retrieve the
Let's rename this NotificationHook.

NotificationHook is a message sent to another service to inform of a change to a Vulnerability or the Ancestries affected by a Vulnerability. It contains the name of a notification that should be read and marked as read via the API.

2017-08-08 19:58 UTC, jzelinskie commented on database/models.go
> +	StartID int
Ideally, this is just a string and we encrypted this before it ever leaves the interface, making it an opaque string to everyone but the implementation of the data store interface.

2017-08-08 19:58 UTC, jzelinskie commented on pkg/strutil/strutil.go
> +package strutil
copyright header

2017-08-08 19:58 UTC, jzelinskie commented on pkg/strutil/strutil_test.go
> +package strutil
copyright header

2017-08-08 19:58 UTC, jzelinskie commented on cmd/clair/main.go
> +	"github.com/coreos/clair/ext/featurens"
import these with `strutil`, `stopper`, etc... leave these only for the side-effect imports that require `_`

2017-08-08 19:58 UTC, jzelinskie commented on cmd/clair/main.go
> +	// prop to user of the current clair registered compontent
I'm not sure what you're trying to say here. Not sure if `prop` is the word you're looking for.

2017-08-08 19:58 UTC, jzelinskie commented on config.example.yaml
> +    enableddetectors:
let's call these `namespace_detectors`

2017-08-08 19:58 UTC, jzelinskie commented on config.example.yaml
> +    enabledlisters:
let's call this `feature_listers`

2017-08-08 19:58 UTC, jzelinskie commented on ext/featurefmt/apk/apk_test.go
> +		},
Does gofmt prevent this?

```go
testFeatures := []database.Feature{
  {Name: "musl", Version: "1.1.14-r10"},
  {Name: "busybox", Version: "1.24.2-r9"},
}
```

2017-08-08 19:58 UTC, jzelinskie commented on ext/featurefmt/driver.go
> +// ListListers returns a list of all listers' names
Let's avoid a tongue twister here:

>ListListers returns the names of all the registered feature listers.

2017-08-08 19:58 UTC, jzelinskie commented on ext/featurens/driver.go
> +func ListDetectors() []string {
>ListDectectors returns the names of all registered namespace detectors.

2017-08-08 19:58 UTC, jzelinskie commented on ext/versionfmt/rpm/parser.go
> +// only for temporary!
o rly

2017-08-08 19:58 UTC, jzelinskie commented on ext/vulnsrc/debian/debian.go
> +	if err := tx.Rollback(); err != nil {
why is this rolling back always here?

2017-08-08 19:58 UTC, jzelinskie commented on ext/vulnsrc/driver.go
> +func ListUpdaters() []string {
>ListUpdaters returns the names of registered vulnerability updaters.

2017-08-08 19:58 UTC, jzelinskie commented on ext/vulnsrc/rhel/rhel.go
> +	tx.Rollback()
why always rollback here?

2017-08-08 19:58 UTC, jzelinskie commented on ext/vulnsrc/ubuntu/ubuntu.go
> +	tx.Rollback()
why always rollback here?

2017-08-08 19:58 UTC, jzelinskie commented on updater.go
> +	return tx.FindLock(updaterLockName)
this is missing a commit?

2017-08-08 19:58 UTC, jzelinskie commented on updater.go
> +
why not defer rollback?

2017-08-08 19:58 UTC, jzelinskie commented on updater.go
> +
why not defer rollback?

2017-08-08 19:58 UTC, jzelinskie commented on worker.go
> +	// TODO: to fix, when there are duplicated layers
hmm

2017-08-08 19:58 UTC, jzelinskie commented on worker.go
>  	}
defer rollback?

2017-08-08 19:58 UTC, jzelinskie commented on worker.go
> +		// at start of the loop, namespaces and features always contain the previous
capital at the start of sentences, end with periods, lol grammar

2017-08-08 19:58 UTC, jzelinskie commented on worker_test.go
> +	"github.com/coreos/clair/ext/featurens"
pull these up to where they used to be

2017-08-09 15:05 UTC, KeyboardNerd commented on database/models.go
> +	StartID int
ok, so in that case the implementation should initialize an encrypted version of
 VulnerabilityNotificationFirstPage and VulnerabilityNotificationLastPage 
when it's registered.

2017-08-09 22:27 UTC, KeyboardNerd commented on ext/vulnsrc/debian/debian.go
> +	if err := tx.Rollback(); err != nil {
Because the transaction won't mutate the database

2017-08-09 22:31 UTC, KeyboardNerd commented on worker.go
> +	// TODO: to fix, when there are duplicated layers
actually the TODO it's not true

2017-08-16 18:41 UTC, jzelinskie commented
I think we should rename the API package to just "api" or "v3" (because Clair v3) in order to avoid confusion.

2017-08-17 17:07 UTC, jzelinskie approved these changes

2017-08-17 17:07 UTC, merged