Reintroduce image scanning for openSUSE and SLE
quay/clair pull request #506
Opened 2018-01-09 20:42 UTC by flavio

As promised inside of https://github.com/coreos/clair/pull/503... handle scanning of openSUSE and SUSE Linux Enterprise images.

The unit tests are passing but I wasn't able to test the code against real images because neither [clair-scanner](https://github.com/arminc/clair-scanner) nor [reg](https://github.com/jessfraz/reg) work against `master`'s new API. Suggestions about how to test the changes are welcome 😃

2018-01-11 20:02 UTC, jzelinskie commented
Thank you so much for reworking all of these changes! I'm really sorry for the slow response.

We don't really have an e2e test framework, and the API changed this release. You can do manual testing by simply using cURL against the API server. It handles both gRPC and JSON over REST.

I'd also like to see some changes to the documentation to include the licensing information for the data in the openSUSE database.

2018-07-09 15:42 UTC, jzelinskie requested changes
This mostly looks good since it's a lot of copypasta from the the RHEL vulnsrc. Ideally after this is merged, we can refactor some of the OVAL parsing into a library decoupled from the particular distribution.

2018-07-09 15:42 UTC, jzelinskie commented on ext/vulnsrc/suse/suse.go
> +	"fmt"
this should be grouped in the first section of imports

2018-07-09 15:42 UTC, jzelinskie commented on ext/vulnsrc/suse/suse.go
> +		panic("Unrecognized flavor")
panic("tried to create an updater for an unrecognized flavor of suse")

2018-07-09 15:42 UTC, jzelinskie commented on ext/vulnsrc/suse/suse.go
> +	log.WithField("flagvalue", flagValue)
This probably needs to be something like Debug level if it stays at all.

2018-07-09 15:42 UTC, jzelinskie commented on ext/vulnsrc/suse/suse.go
> +	latestOval, _ := strconv.ParseInt(flagValue, 10, 64)
Why ignore this error?

2018-07-09 15:42 UTC, jzelinskie commented on ext/vulnsrc/suse/suse.go
> +			}).Debug("file to check")
```go
	log.WithFields(log.Fields{
		"ovalFile": ovalFile,
		"updater":  u.Name,
	}).Debug("file to check")
```

2018-07-09 15:42 UTC, jzelinskie commented on ext/vulnsrc/suse/suse.go
> +		// do not fetch the entire file to get the value of the
Do

2018-07-09 15:42 UTC, jzelinskie commented on ext/vulnsrc/suse/suse.go
> +	layout := "Mon, 2 Jan 2006 15:04:05 MST"
pull this out into a constant `timeFormatLastModified`

2018-07-09 15:42 UTC, jzelinskie commented on ext/vulnsrc/suse/suse.go
> +		}
`defer r.Body.Close()` or make sure to put `r.Body.Close()` before any return/continue statements

2018-07-09 15:42 UTC, jzelinskie commented on ext/vulnsrc/suse/suse.go
> +	layout := "2006-1-2T15:04:05"
pull this out into a constant `timeFormatOVAL`

2018-07-09 15:42 UTC, jzelinskie commented on ext/vulnsrc/suse/suse.go
> +					//TODO: handle that once openSUSE/SLE OVAL files have severity info
pull this out into a function `severity(definition)` that doesn't do anything but return UnknownSeverity, and has this comment.

2018-07-09 15:42 UTC, jzelinskie commented on ext/vulnsrc/suse/suse.go
> +				if len(match) != 4 {
it's easier to read this conditional if you keep it `if (positive case) else negative case`.

```go
if len(match) == 4 {
  osVerison = ...
} else {
  log.WithField().Warning()
}
```

2018-07-09 15:42 UTC, jzelinskie commented on ext/vulnsrc/suse/suse.go
> +
get rid of this new line

2018-07-09 15:42 UTC, jzelinskie commented on ext/vulnsrc/suse/suse_test.go
> +		"runc-0.1.1+gitr2816_02f8fa7 is installed":                    []string{"runc", "0.1.1+gitr2816_02f8fa7"},
add some tests for the failure scenario

2018-09-25 19:26 UTC, flavio commented
@jzelinskie sorry for the late response... I've implemented all the changes you requested. Once you are fine with the changes I'll rebase this branch against master and squash all the commits into a single one.

:heart:

2018-11-14 19:09 UTC, jzelinskie requested changes
couple of tiny nitpicks, but feel free to rebase now

2018-11-14 19:09 UTC, jzelinskie commented on ext/vulnsrc/suse/suse.go
> +		log.Fatal(err)
This shouldn't be fatal.

2018-11-14 19:09 UTC, jzelinskie commented on ext/vulnsrc/suse/suse.go
> +		}
This for-loop can be done in one line:

```go
resp.Vulnerabilities = append(resp.Vulnerabilities, vs...)
```

2018-11-14 19:09 UTC, jzelinskie commented on ext/vulnsrc/suse/suse.go
> +			}
This for-loop can be done in one line:

```go
vulnerability.Affected = append(vulnerability.Affected, pkgs...)
```

2018-11-14 19:09 UTC, jzelinskie commented on ext/vulnsrc/suse/suse.go
> +				name, version, err := splitPackageNameAndVersion(c.Comment[:len(c.Comment)-13])
In order to make it obvious where `13` is coming from: `len(c.Comment)-len(" is installed")`

2018-11-15 09:57 UTC, flavio commented
@jzelinskie I've update the code with the changes you proposed. Take a look at the changes I made and gimme the final green light for the rebase.

2018-11-19 16:36 UTC, jzelinskie commented
I don't want this to hang any longer. Rebase away!

2018-11-20 07:21 UTC, flavio commented
> I don't want this to hang any longer. Rebase away!

@jzelinskie done!

2018-11-22 16:13 UTC, flavio commented
I did another forced push to address the style check errors reported by `goftm`.

2018-12-17 12:39 UTC, Payback159 commented
Hi Guys, any forecast when this feature will be available?

2019-01-04 19:18 UTC, jzelinskie commented
Sorry for the silence around the holidays. This code all looks fine. I think all this PR needs is to add OpenSUSE to the documentation in a few places. Most importantly here: https://github.com/coreos/clair/blob/master/Documentation/drivers-and-data-sources.md#data-sources-for-the-built-in-drivers

2019-01-07 17:50 UTC, flavio commented
@jzelinskie I did a rebase against master and then added a new commit which extends the documentation. Thanks for pointing that out. AFAIK this is the only place of the documentation that needs to be extended.

2019-01-07 18:21 UTC, jzelinskie approved these changes
Yay! Let's get this ball rolling!

2019-01-07 18:21 UTC, merged