Improvements to the helm chart
quay/clair pull request #522
Opened 2018-02-09 12:37 UTC by vdboor

With this PR I'd like to fix the hurdles I've run into.

These are:
* one bug: the `source: postgresURI ` line was merged the the comment above, because the if statement strips newlines at both ends.
* the memory limits are too low, causing Clair to be scheduled on hosts that doesn't have enough memory available - and eventually OOM the container or machine.
* Switch to the stable release, as the git version doesn't work out of the box.
* Explicitly mention that `postgresql.enabled` can be set to false, because the `requirements.yaml` allows that.

2018-02-10 01:11 UTC, jzelinskie requested changes
Just one minor nitpick.
Thanks a bunch for giving this some love.

2018-02-10 01:11 UTC, jzelinskie commented on contrib/helm/clair/values.yaml
> +  tag: v2.0.1
Because this code is in master, it should be tied to deploying master. When we cut a stable release, we should tie this to a particular version.

2018-02-12 10:20 UTC, vdboor commented
Thanks for looking into this. I've updated my pull request to omit that image change!

I do think it might be useful to mention this in the docs, so people can choose to install the stable version instead. I didn't get the master version running last week.

2018-02-12 16:47 UTC, jzelinskie approved these changes
Agreed. Can you file an issue?

2018-02-12 16:47 UTC, merged