vulnsrc/oracle,vulnsrc/rhel: speed up first update
quay/clair pull request #602
Opened 2018-08-31 10:31 UTC by slmint

Using the bzip2 files provided by rhsa and oracle ([com.redhat.rhsa-all.xml.bz2](https://www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml.bz2) and [com.oracle.elsa-all.xml.bz2](https://linux.oracle.com/security/oval/com.oracle.elsa-all.xml.bz2)) can reduce the time taken for the initial update and avoid triggering the restriction policy.

---
使用rhsa和oracle提供的bzip2文件([com.redhat.rhsa-all.xml.bz2](https://www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml.bz2)和[com.oracle.elsa-all.xml.bz2](https://linux.oracle.com/security/oval/com.oracle.elsa-all.xml.bz2))，可以使初次更新的耗时降低，也可以避免触发限制策略

2018-09-04 18:11 UTC, jzelinskie requested changes
I'm kinda hesitant to include this because we've had issues in the past where poor network connectivity has made downloading one giant blob impossible.

2018-09-04 18:11 UTC, jzelinskie commented on ext/vulnsrc/oracle/oracle.go
> +	cmd := exec.Command("bunzip2", elsaFilePrefix+"all.xml.bz2")
You should use `golang.org/pkg/compress/bzip2` rather than `exec`.

2018-09-04 18:11 UTC, jzelinskie commented on ext/vulnsrc/oracle/oracle.go
> +	if r.StatusCode == 404 {
Why is the 404 case before `err != nil`?
Checking the error and `defer r.Body.Close()` should happen before checking status codes.

2018-09-04 18:11 UTC, jzelinskie commented on ext/vulnsrc/oracle/oracle.go
> +		log.WithField("package", "Oracle Linux").Error("repsonse status code isn't 200")
s/repsonse/response

Include the file name in the Fields.

2018-09-04 18:11 UTC, jzelinskie commented on ext/vulnsrc/oracle/oracle.go
> +		log.WithField("package", "Oracle Linux").Warnf("%sall.xml.bz2 not found, try fetch each xml", elsaFilePrefix)
Put the filename as a field instead of the message.
The message should be constant.

2018-09-04 18:11 UTC, jzelinskie commented on ext/vulnsrc/oracle/oracle.go
> +		log.WithError(err).Error("could not download ELSA's update list")
Include the package in the fields.

2018-09-04 18:11 UTC, jzelinskie commented on ext/vulnsrc/oracle/oracle.go
> +	log.WithField("package", "Oracle Linux").Infof("Parse %sall.xml.bz2", elsaFilePrefix)
Put the filename as a field instead of the message.
The message should be constant.

2018-09-05 10:46 UTC, slmint commented
Is it better to handle the timeout and limit the response body size in httputil?

[http.Client.Timeout ](https://golang.org/src/net/http/client.go#L89)   and [io.LimitedReader](https://golang.org/pkg/io/#LimitedReader)

---
在httputil中处理超时和限制读取的响应Body大小会更合适？

2018-11-15 05:14 UTC, closed without merging