Using httputil for NVD
quay/clair pull request #610
Opened 2018-09-06 20:05 UTC by MackJM

nvd was missed when moving to httputil, this fixes it

2018-09-06 20:14 UTC, jzelinskie requested changes

2018-09-06 20:14 UTC, jzelinskie commented on ext/vulnmdsrc/nvd/nvd.go
> +			// r is closed in BuildCache()
not if an error occurs

2018-09-06 20:14 UTC, jzelinskie commented on ext/vulnmdsrc/nvd/nvd.go
> +		return "", errors.New("Unsuccesuful status code: " + string(r.StatusCode))
`Unsuccessful`

Also having some more context in this message would be nice. I have no idea what request was being tried that returned a non-200 status code.

2018-09-07 14:53 UTC, MackJM commented
I was wrong at first with that comment, because that's where it crashed when I had defer there.

2018-09-07 20:20 UTC, jzelinskie commented on ext/vulnmdsrc/nvd/nvd.go
> +			defer r.Body.Close()
This won't close anything until the whole function getDataFeeds() exits. This is not what we want to do.

It could end up being more trouble than it's worth, but wrapping everything inside the loop iteration into a it's own function might be the best way to get defer to execute at the right time.

2018-09-07 21:18 UTC, MackJM commented on ext/vulnmdsrc/nvd/nvd.go
> +			defer r.Body.Close()
Yeah, it was a little outside of what I set out with my initial PR, but I agree with you. I think I wrapped it up nicely now. Without spending too much effort.

2018-09-10 17:12 UTC, jzelinskie requested changes

2018-09-10 17:12 UTC, jzelinskie commented on ext/vulnmdsrc/nvd/nvd.go
> +			downloadAndSave := func() error {
I think you should pull this out into a top-level function called downloadFeed, rather than an inline function. After that LGTM.

2018-09-11 19:24 UTC, jzelinskie requested changes

2018-09-11 19:24 UTC, jzelinskie commented on ext/vulnmdsrc/nvd/nvd.go
> +
Sorry for the OCD, but drop this newline and we're good to go.

2018-09-19 18:25 UTC, jzelinskie approved these changes

2018-09-19 18:25 UTC, merged