pkg/gitutil: init
quay/clair pull request #621
Opened 2018-09-14 21:27 UTC by jzelinskie

This refactors the code we're using to manage temporary git repositories
into a utility package.

2018-09-15 00:48 UTC, KeyboardNerd requested changes

2018-09-15 00:48 UTC, KeyboardNerd commented on ext/vulnsrc/alpine/alpine.go
Wow.
Very duplication.
So Git.

2018-09-15 00:48 UTC, KeyboardNerd commented on pkg/gitutil/gitutil.go
> +		os.RemoveAll(path)
log returned error

yeah, previously it wasn't handled at all.

2018-09-15 00:48 UTC, KeyboardNerd commented on pkg/gitutil/gitutil.go
> +		path, err = ioutil.TempDir(os.TempDir(), remote)
I don't think we should use `remote` for the prefix 
https://github.com/coreos/clair/pull/621/files#diff-154f97505971bb2f44a0f30045d133d2R38
We can use the updater flag I think.

2018-09-15 00:48 UTC, KeyboardNerd commented on pkg/gitutil/gitutil.go
> +// to that path.
Different from the documentation here, the code only generate a new temporary directory when the desired path is not given. Is that the expected behavior?

2018-09-17 22:28 UTC, jzelinskie commented on ext/vulnsrc/alpine/alpine.go
[![](https://camo.githubusercontent.com/aec4c3fc2d674f2a4e90ed9e1413d95f204d7445/687474703a2f2f692e696d6775722e636f6d2f48784839716b612e706e67)](https://github.com/thiderman/doge)

2018-09-18 14:23 UTC, KeyboardNerd requested changes

2018-09-18 14:23 UTC, KeyboardNerd commented on pkg/gitutil/gitutil.go
> +		path, err = ioutil.TempDir(os.TempDir(), remote)
remote -> tempDirPrefix

2018-09-18 14:23 UTC, KeyboardNerd commented on pkg/gitutil/gitutil.go
> +// desiredPath. Otherwise, it performs a git clone to that path.
nit: desired path?

2018-09-26 15:42 UTC, KeyboardNerd approved these changes

2018-09-26 15:42 UTC, merged