Switch to NVD JSON feed and include CVSSv3
quay/clair pull request #645
Opened 2018-10-17 15:31 UTC by Katee

The NVD JSON feed is still "beta". According to the [NVD changlog](https://nvd.nist.gov/vuln/Data-Feeds/JSON-feed-changelog) the last breaking change (a field rename which would not have affected this code) happened 2017-12-18. **CVSSv3 is only in the JSON feed.**

Some things in the feed relevant to Clair have changed:
* The format for `PublishedDateTime` has changed from `2018-01-10T17:29:00.930-05:00` to `2018-01-10T22:29Z`.
* The CVSSv2 and CVSSv3 vector strings are provided directly. If desired, I'm happy to remove the parsing code here or in another PR.

The changes in this PR are meant to be backwards compatible:
* `NVDmetadataCVSSv2` remains unchanged. `PublishedDateTime` is still in `NVDmetadataCVSSv2` even though it isn't specific to CVSSv2.
* As before, `Metadata` returns nil if CVSSv2 isn't available (and this now has a test).

2018-10-17 16:38 UTC, skelterjohn commented on ext/vulnmdsrc/nvd/json.go
> +type nvd struct {
Is there a reason you chose to not export any of these type names? Specifically, it means that code in another package cannot construct one of these unless it takes a json blob and runs it through the parser. Constructing them directly can be useful for testing.

2018-10-17 18:25 UTC, Katee commented on ext/vulnmdsrc/nvd/json.go
> +type nvd struct {
This matches the previous `xml.go` file. The purpose of having these structs unexported is so changes to the underlying feed don't require a change to Clair's data model. Other packages should only be depending on Clair's data models, not this intermediate representation.

In `nvd.go` the `NVDmetadataCVSSv3` struct could be changed to include all the CVSSv3 fields, depends on what the Clair maintainers want.

Tests in the same package have access even if things are not exported.

2018-10-18 20:44 UTC, jzelinskie requested changes
just two minor nitpicks

2018-10-18 20:44 UTC, jzelinskie commented on ext/vulnmdsrc/nvd/json.go
> +// Copyright 2017 clair authors
```suggestion
// Copyright 2018 clair authors
```

2018-10-18 20:44 UTC, jzelinskie commented on ext/vulnmdsrc/nvd/json.go
> +var vectorValuesToLetters map[string]string
No need to use `init()`:

```suggestion
var vectorValuesToLetters = map[string]string{
	"NETWORK":          "N",
	"ADJACENT_NETWORK": "A",
	"LOCAL":            "L",
	"HIGH":             "H",
	"MEDIUM":           "M",
	"LOW":              "L",
	"NONE":             "N",
	"SINGLE":           "S",
	"MULTIPLE":         "M",
	"PARTIAL":          "P",
	"COMPLETE":         "C",

	// CVSSv3 only
	"PHYSICAL":  "P",
	"REQUIRED":  "R",
	"CHANGED":   "C",
	"UNCHANGED": "U",
}
```

2018-10-19 14:41 UTC, Katee commented
I'd also like to pass through the CVSSv3 expoloitability score and impact score, I'm adding a commit for that now.

2018-10-19 15:10 UTC, jzelinskie commented on ext/vulnmdsrc/nvd/json.go
> +}
I couldn't figure out how to make the GitHub suggestion delete this, too. ☹️

2018-10-19 19:00 UTC, Katee commented on ext/vulnmdsrc/nvd/json.go
> +}
Whoops! I didn't notice that merging from the GitHub UI. Fixed. (Do you want any history re-written?)

2018-10-22 17:03 UTC, jzelinskie approved these changes

2018-10-22 17:03 UTC, merged