Add updaters for Amazon Linux 2018.03 and Amazon Linux 2
quay/clair pull request #671
Opened 2018-12-11 23:38 UTC by ericysim

We get vulnerabilities from ALAS (Amazon Linux Security Advisories) data, which can be found in updateinfo.xml from the repos.

---

Here's ALAS data in a human-readable format: https://alas.aws.amazon.com/

We don't use https://alas.aws.amazon.com/ for the updater. Instead, we use updateinfo.xml from the repos, which has the same information (and more) in XML format.

Here's how to get the URL of updateinfo.xml.gz. We have to do this because the hash in the URL changes whenever there's a push.

> - Get the mirror.list URL, which is found in the repo definitions in /etc/yum.repos.d.
>   - e.g. http://repo.us-west-2.amazonaws.com/2018.03/updates/x86_64/mirror.list
> - Get the first line of mirror.list; this is the base URL.
>   - e.g. http://packages.us-west-2.amazonaws.com/2018.03/updates/9f831135fa79/x86_64
> - Append repodata/repomd.xml to the base URL. This XML file defines the metadata available in the repo.
>   - e.g. http://packages.us-west-2.amazonaws.com/2018.03/updates/9f831135fa79/x86_64/repodata/repomd.xml
> - Find a data element with type="updateinfo" and follow the location relative to the base URL.
>    - e.g. http://packages.us-west-2.amazonaws.com/2018.03/updates/9f831135fa79/x86_64/repodata/updateinfo.xml.gz

We do this process in the code.

Question: I'd like the mirror.list URLs to be user-configurable (e.g. http://repo.us-east-2.amazonaws.com/2018.03/updates/x86_64/mirror.list instead of http://repo.us-west-2.amazonaws.com/2018.03/updates/x86_64/mirror.list). What's a good way to do this?

2018-12-12 19:34 UTC, KeyboardNerd commented
Currently, the updaters are not configurable. We can make updaters configurable per updater base in the future, but it's not the current goal.

2018-12-12 21:11 UTC, ericysim commented
I see; it's no problem :)

2019-01-11 05:17 UTC, subash-canapathy commented
Can someone tag an approver to review this. We want to be enable scans for amazon linux containers

2019-03-12 20:12 UTC, subash-canapathy approved these changes
Looks good to me, passes tests.

2019-03-21 18:52 UTC, ericysim commented
How can we get traction on this pull request? @jzelinskie @KeyboardNerd

2019-03-21 19:12 UTC, KeyboardNerd commented
This looks really cool.
What the license is the vuln source is under? 
We'd like to enable people to use Clair in both commercial or non-commercial settings.

2019-03-22 16:22 UTC, ilianaw commented
Hi, I work on Amazon Linux.

> What the license is the vuln source is under?

The vulnerability data (updateinfo.xml files in our repositories) are free to use.

If you need a more specific answer I'll need to do a query to our legal folks, but there is certainly no non-commercial restriction on the data.

2019-03-22 19:38 UTC, KeyboardNerd commented
Thanks, we'll review the code.

2019-04-10 00:35 UTC, jzelinskie requested changes
I'm really sorry for the delay on the review. Honestly, I only have very small style nitpicks. The rest looks great! There's a lot of rpm-based updaters, we should eventually write some shared plumbing for them, but for right now this is perfect.

edit: actually one more thing, you need to add Amazon Linux in the documentation for supported platforms along with the licensed for the data being used.

2019-04-10 00:35 UTC, jzelinskie commented on ext/vulnsrc/amzn/amzn.go
> +	"fmt"
this should be with all the other stdlib imports

2019-04-10 00:35 UTC, jzelinskie commented on ext/vulnsrc/amzn/amzn.go
> +	amazonLinux2UpdaterFlag   = "amazonLinux2Updater"
put an extra new line above this line so that AL1 has its own block and AL2 has its own block

2019-04-10 00:35 UTC, jzelinskie commented on ext/vulnsrc/amzn/amzn.go
> +// Copyright 2017 clair authors
It's not 2017 anymore!

2019-04-11 20:42 UTC, ericysim commented on ext/vulnsrc/amzn/amzn.go
> +	"fmt"
done

2019-04-11 20:42 UTC, ericysim commented on ext/vulnsrc/amzn/amzn.go
> +	amazonLinux2UpdaterFlag   = "amazonLinux2Updater"
done

2019-04-11 20:42 UTC, ericysim commented on ext/vulnsrc/amzn/amzn.go
> +// Copyright 2017 clair authors
done

2019-04-11 20:43 UTC, ericysim commented
Thanks @jzelinskie, I made the recommended changes.

2019-04-11 22:51 UTC, ericysim commented
> edit: actually one more thing, you need to add Amazon Linux in the documentation for supported platforms along with the licensed for the data being used.

Ok, will do. I will ask @iliana about the license again.

2019-04-23 17:18 UTC, subash-canapathy commented
@ericysim - Hi Eric is this now ready to be merged.

2019-04-23 17:26 UTC, ericysim commented
Hi @subash-canapathy, I got the license info this morning. I'm going to add Amazon Linux to the docs and push a commit by the end of the day :)

2019-04-23 17:44 UTC, ericysim commented
Hi @jzelinskie, I made the recommended changes.

2019-04-24 18:10 UTC, jzelinskie approved these changes

2019-04-24 18:11 UTC, merged