Replace arrays with slices
quay/clair pull request #680
Opened 2019-01-02 12:06 UTC by Allda

This solution should be easier to read and maintain because there is no need of using indexes.

NOTE: There are few more places which use indexes. If this PR will be approved I can refactor rest of codebase.

2019-01-10 18:58 UTC, jzelinskie commented
I suspect that based on the comment above the code:
```go
// TODO(Sida): A better interface for bulk insertion is needed.
```
This is done for performance reasons. `append` is going to allocate whenever adding the new value will exceed the existing `cap`, then it'll double the size of the slice.

The existing code allocates only once.

2019-01-14 18:54 UTC, jzelinskie commented
Btw, we can get the best of both worlds with code like this:
```go
keys := make([]interface{}, len(features)*3)
for _, f := range features {
  keys = append(keys, f.Name, f.Version, f.VersionFormat)
  ...
}
```

2019-01-14 18:59 UTC, jzelinskie requested changes
I think we can get the best of both worlds by keeping the usage of `make`, followed by using `append`.

```go
keys := make([]interface{}, len(features)*3)
for _, f := range features {
  keys = append(keys, f.Name, f.Version, f.VersionFormat)
  ...
}
```

2019-01-14 18:59 UTC, jzelinskie commented on database/pgsql/layer.go
> +	// keys := make([]interface{}, len(features)*3)
why comment this out? this is probably what we want to keep rather than `var keys []interface{}`, which introduces the possibility of a nil slice.

2019-01-14 18:59 UTC, jzelinskie commented on database/pgsql/feature.go
> +		keys = append(keys,
Let's keep the append on one line.

2019-01-15 14:42 UTC, Allda commented
This doesn't seem to work because make([]interface{}, len(features)*3) creates a slice with default values and append() adds items at the end.

2019-01-15 21:13 UTC, jzelinskie commented
Ah, you probably have to do `make([]interface{}, 0, len(features)*3)` so that you set the capacity and not the length.

2019-01-17 10:59 UTC, Allda commented
Now it works fine after setting just capacity.

2019-01-22 22:01 UTC, jzelinskie approved these changes

2019-01-22 22:01 UTC, merged